main/urls.py
from django.urls import path
from .views import *
from . import views


urlpatterns = [
    path('', MainPageView.as_view(), name='home'),
    path('category/<str:slug>/', CategoryDetailView.as_view(), name='category'),
    path('product-detail/<int:pk>/', ProductDetailView.as_view(), name='product-detail'),
    path('add-product/', ProductCreateView.as_view(), name='add-product'),
    path('update-product/<int:pk>/', ProductUpdateView.as_view(), name='update-product'),
    path('delete-product/<int:pk>/', DeleteProductView.as_view(), name='delete-product'),
    path('filter-product/', FilterPageView.as_view(), name='filter-product'),
    path('search/', SearchPageView.as_view(), name='search'),

    # cart urls
    path('cart/add/<int:id>/', views.cart_add, name='cart_add'),
    path('cart/item_clear/<int:id>/', views.item_clear, name='item_clear'),
    path('cart/item_increment/<int:id>/',
         views.item_increment, name='item_increment'),
    path('cart/item_decrement/<int:id>/',
         views.item_decrement, name='item_decrement'),
    path('cart/cart_clear/', views.cart_clear, name='cart_clear'),
    path('cart/cart-detail/', views.cart_detail, name='cart_detail'),
]

main/models.py
from django.db import models

from account.models import User


class Category(models.Model):
    slug = models.SlugField(primary_key=True, max_length=50)
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='categories', blank=True, null=True)
    parent = models.ForeignKey('self', related_name='children', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        if self.parent:
            return f"{self.parent} -> {self.name}"
        return self.name

    @property
    def get_children(self):
        if self.children:
            return self.children.all()
        return False


class Product(models.Model):
    ENGINE_CHOICES = [
        ('petrol', 'Бензин'),
        ('diesel', 'Дизель'),
        ('electro', 'Электро'),
        ('hybrid', 'Гибрид'),
        ('diesel gas', 'Дизель+газ'),
        ('petrol gas', 'Бензин+газ'),
        ('gas', 'Газ'),
        ('not specified', 'Не указано'),
    ]

    STEERING_WHEEL_CHOICES = [
        ('right', 'Правый'),
        ('left', 'Левый'),
    ]

    TRANSMISSION_CHOICES = [
        ('automatic', 'Автомат'),
        ('mechanical', 'Механическая'),
        ('pneumatic', 'Пневматическая'),
        ('robot', 'Робот'),
        ('variable', 'Вариатор'),
        ('not specified', 'Не указано'),
    ]

    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name="products")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='products')
    name = models.CharField(max_length=255, verbose_name="Наименование")
    description = models.TextField(blank=True)
    image = models.ImageField(upload_to='products')
    price = models.DecimalField(max_digits=20, decimal_places=2, verbose_name='Цена')
    # discount = models.PositiveIntegerField(verbose_name='Скидка, %', default=0)
    year_of_issue = models.PositiveIntegerField(verbose_name='Год выпуска')
    mileage = models.PositiveIntegerField(verbose_name='Пробег, км', default=0)
    engine = models.CharField(choices=ENGINE_CHOICES,
                              max_length=30, default='not specified', verbose_name='Двигатель')
    number_of_seats = models.PositiveIntegerField(verbose_name='Количство мест')
    volume = models.DecimalField(max_digits=9, decimal_places=2, verbose_name='Объём двигателя, см3')
    power = models.PositiveIntegerField(verbose_name='Мощность, л. с.')
    transmission = models.CharField(choices=TRANSMISSION_CHOICES,
                                    max_length=20, default='not specified', verbose_name='Коробка')
    steering_wheel = models.CharField(choices=STEERING_WHEEL_CHOICES,
                                      max_length=20, default='left', verbose_name='Руль')
    color = models.CharField(max_length=255, verbose_name='Цвет')
    created = models.DateTimeField()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('product-detail', kwargs={'pk': self.pk})

templates/add-product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Раздел добавления нового продукта -->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div style="max-width: 500px; margin: 0 auto;">
            <h1 class="jumbotron-heading" style="margin-bottom: 50px;">Добавить новый продукт</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ product_form|crispy }}
                {{ formset.management_form }}
                {% for form in formset %}
                    {{ form }}
                {% endfor %}
                <button type="submit" class="btn btn-secondary btn-lg btn-block" style="width: 100%; position: relative; top: 25px; margin-bottom: 50px;">Добавить</button>
            </form>
        </div>
    </div>
</section>
<!-- /Раздел добавления нового продукта -->
{% endblock %}

templates/category-detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section class="py-5" id="features">
	<h1 style="text-align: center; margin-bottom: 50px;">Категория: {{ category.name }}</h1>
	{% if category.get_children %}
	<div class="container px-5 my-5">
		<div class="row gx-5">
			{% for child in category.get_children %}
			<div class="col-lg-4 mb-5 mb-lg-0">
				<div class="feature bg-primary bg-gradient text-white rounded-3 mb-3"><i class="bi bi-collection"></i>
				</div>
				<h2 class="h4 fw-bolder">{{ child.name }}</h2>
				<p>Paragraph of text beneath the heading to explain the heading. We'll add onto it with another sentence
					and probably just keep going until we run out of words.</p>
				<a class="text-decoration-none" href="{% url 'category' child.slug  %}">
					Перейти
					<i class="bi bi-arrow-right"></i>
				</a>
			</div>
			{% endfor %}
		</div>
	</div>

	{% else %}
	<div class="album" style="outline: none;">
		<div class="container">
			<div class="row">
				{% if products %}
				{% for product in products %}
				<div class="col-md-4" style="margin: 0 auto;">
					<div class="card mb-4 box-shadow">
						<img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.title }}">
						<div class="card-body">
							<p class="card-text">
							<h5 style="text-align: center; margin: 0 0 15px;">{{ product }}</h5>
							Год выпуска: {{ product.year_of_issue }},
							Пробег, км: {{ product.mileage }},
							Двигатель: {{ product.get_engine_display }},
							Объем двигателя, см3: {{ product.volume }},
							Мощность, л. с.: {{ product.power }} ...
							<hr>
							<h5 style="text-align: center; padding: 0 0 14px;">{{ product.price }} сом</h5>
							</p>
							<div class="d-flex justify-content-between align-items-center">
								<div class="btn-group">
									<a href="{% url 'cart_add' product.id %}"
									   class="btn btn-sm btn-outline-secondary">В корзину</a>
									<a href="{% url 'product-detail' product.id %}"
									   class="btn btn-sm btn-outline-secondary">Перейти</a>
								</div>
								<small class="text-muted">{{ product.created }}</small>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				{% else %}
				<h3>Упс... кажется нет публикаций((</h3>
				{% endif %}
			</div>
		</div>
	</div>
	{% endif %}
</section>
{% endblock %}


templates/delete-product.html
{% extends 'base.html' %}
{% block content %}

<form method="POST" enctype="multipart/form-data" role="main" style="padding: 60px 0 30px;">
    {% csrf_token %}
      <section class="jumbotron text-center">
        <div class="container">
          <h1 class="jumbotron-heading">Удаление продукта из Базы Данных.</h1>
          <p class="lead text-muted">Вы действительно хотите удалить данный продукт?</p>
          <p>
            <button type="submit" class="btn btn-primary my-2">Да, удалить</button>
            <a href="{% url 'home' %}" class="btn btn-secondary my-2">Отменить</a>
          </p>
        </div>
      </section>

      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
            <div class="col-md-4" style="margin: 0 auto;">
              <div class="card mb-4 box-shadow">
                <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product }}">
                <div class="card-body">
                  <p class="card-text">
                      <h5 style="text-align: center; margin: 0 0 15px;">Mersedes-Benz {{ product }}</h5>
                    Год выпуска: {{ product.year_of_issue }},
                    Пробег, км: {{ product.mileage }},
                    Двигатель: {{ product.get_engine_display }},
                    Объем двигателя, см3: {{ product.volume }},
                    Мощность, л. с.: {{ product.power }} ...
                      <hr>
                  <h5 style="text-align: center; padding: 0 0 14px;">{{ product.price }} сом</h5>
                  </p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <a  href="{% url 'update-product' product.id %}" class="btn btn-sm btn-outline-secondary">Обновить</a>
                    </div>
                    <small class="text-muted">{{ product.created }}</small>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
</form>

{% endblock %}

templates/filter-product.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<section class="py-5" id="features">
	<h1 style="text-align: center; margin-bottom: 50px;">Фильтр: {{ category }}</h1>
	<div class="album" style="outline: none;">
		<div class="container">
			<div class="row">
				{% if products %}
				{% for product in products %}
				<div class="col-md-4" style="margin: 0 auto;">
					<div class="card mb-4 box-shadow">
						<img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.title }}">
						<div class="card-body">
							<p class="card-text">
							<h5 style="text-align: center; margin: 0 0 15px;">{{ product }}</h5>
							Год выпуска: {{ product.year_of_issue }},
							Пробег, км: {{ product.mileage }},
							Двигатель: {{ product.get_engine_display }},
							Объем двигателя, см3: {{ product.volume }},
							Мощность, л. с.: {{ product.power }} ...
							<hr>
							<h5 style="text-align: center; padding: 0 0 14px;">{{ product.price }} сом</h5>
							</p>
							<div class="d-flex justify-content-between align-items-center">
								<div class="btn-group">
									<a href="{% url 'cart_add' product.id %}"
									   class="btn btn-sm btn-outline-secondary">В корзину</a>
									<a href="{% url 'product-detail' product.id %}"
									   class="btn btn-sm btn-outline-secondary">Перейти</a>
								</div>
								<small class="text-muted">{{ product.created }}</small>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
				{% else %}
				<h3>Упс... кажется нет публикаций((</h3>
				{% endif %}
			</div>
		</div>
	</div>
</section>
{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}
{% block content %}

{% if messages %}
    {% for message in messages %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
          {{ message }}
          <span style="float: right;">X
          </span>
        </div>
    {% endfor %}
{% endif %}

<!-- Section-->
<section class="py-5" id="features">
    <h1 style="text-align: center; margin-bottom: 50px;">Главная страница</h1>
	<div class="album" style="outline: none;">
		<div class="container">
			<div class="row">
                {% if products %}
                {% for product in page_obj %}
                <div class="col-md-4" style="margin: 0 auto;">
                        <div class="card mb-4 box-shadow">
                            <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product.title }}">
                            <div class="card-body">
                                <p class="card-text">
                                <h5 style="text-align: center; margin: 0 0 15px;">{{ product }}</h5>
                                Год выпуска: {{ product.year_of_issue }},
                                Пробег, км: {{ product.mileage }},
                                Двигатель: {{ product.get_engine_display }},
                                Объем двигателя, см3: {{ product.volume }},
                                Мощность, л. с.: {{ product.power }} ...
                                <hr>
                                <h5 style="text-align: center; padding: 0 0 14px;">{{ product.price }} сом</h5>
                                </p>
                                <div class="d-flex justify-content-between align-items-center">
                                    <div class="btn-group">
                                        <a href="{% url 'cart_add' product.id %}"
                                           class="btn btn-sm btn-outline-secondary">В корзину</a>
                                        <a href="{% url 'product-detail' product.id %}"
                                           class="btn btn-sm btn-outline-secondary">Перейти</a>
                                    </div>
                                    <small class="text-muted">{{ product.created }}</small>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                {% else %}
                <h3>Упс... кажется нет публикаций((</h3>
                {% endif %}
            </div>
        </div>
    </div>
</section>

<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
      {% if page_obj.has_previous %}
    <li class="page-item">
      <a class="page-link" href="{% url 'home' %}?page={{ page_obj.previous_page_number }}">Предыдущий</a>
    </li>
      {% endif %}
    <li class="page-item"><a class="page-link" href="#">{{ page_obj.number }}</a></li>
      {% if page_obj.has_next %}
    <li class="page-item">
      <a class="page-link" href="{% url 'home' %}?page={{ page_obj.next_page_number }}">Следующий</a>
    </li>
      {% endif %}
  </ul>
</nav>

{% endblock %}


templates/product-detail.html
{% extends 'base.html' %}
{% load static %}
{% load mathfilters %}
{% block content %}

<!-- Раздел описания продукта -->
<section class="py-5">
    <div class="container px-4 px-lg-5 my-5">
        <div class="row gx-4 gx-lg-5 align-items-center">
            <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" src="{{ product.image.url }}" alt="{{ product.title }}"/></div>
            <div class="col-md-6">
                <div class="small mb-1">Дата публикации: {{ product.created }}</div>
                <h1 class="display-5 fw-bolder">{{ product }}</h1>
                <div class="fs-5 mb-5">
                    {% if product.discount %}
                    <span class="text-decoration-line-through" style="color: red;">{{ product.price }}</span>
                    <span>{{ product.price|mul:product.discount|div:-100|add:product.price }} сом</span>
                    {% else %}
                    <span>{{ product.price }} сом</span>
                    {% endif %}
                </div>
                <p class="lead">
                    <b>Год выпуска:</b> {{ product.year_of_issue }}<br>
                    <b>Пробег, км:</b> {{ product.mileage }}<br>
                    <b>Двигатель:</b> {{ product.get_engine_display }}<br>
                    <b>Количество мест:</b> {{ product.number_of_seats }}<br>
                    <b>Объем двигателя, см3:</b> {{ product.volume }}<br>
                    <b>Мощность, л. с.:</b> {{ product.power }}<br>
                    <b>Коробка:</b> {{ product.get_transmission_display }}<br>
                    <b>Руль:</b> {{ product.get_steering_wheel_display }}<br>
                    <b>Цвет:</b> {{ product.color }}<br>
                    <i>{{ product.description }}</i>
                </p>
                <div class="d-flex">
                    <div class="btn-group" role="group" aria-label="Basic example">
                      <a href="{% url 'cart_add' product.id %}" class="btn btn-secondary">В корзину</a>
                         {% if request.user.is_authenticated and request.user.is_superuser %}
                      <a class="btn btn-secondary btn-success" href="{% url 'update-product' product.id %}">Обновить</a>
                      <a class="btn btn-secondary btn-danger" href="{% url 'delete-product' product.id %}">Удалить</a>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- /Раздел описания продукта -->

<!-- Related items section-->
<section class="py-5 bg-light">
    <div class="container px-4 px-lg-5 mt-5">
        <h2 class="fw-bolder mb-4">Новые машины</h2>
        {% if products_new %}
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in products_new %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product }}"/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h6 class="fw-bolder">{{ product|truncatewords:5 }}</h6>
                            <p>{{ product.power }} л.с, {{ product.volume }} АТ, {{ product.year_of_issue }} г.
                            {{ product.mileage }} км, {{ product.get_transmission_display }}</p>
                            <!-- Product price-->
                            <h6>{{ product.price }} сом</h6>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product-detail' product.id %}">Посмотреть</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p>Упс... Пока нет новых машин</p>
        {% endif %}

        <h2 class="fw-bolder mb-4">Леворульные машины</h2>
        {% if products_left_steering_wheel %}
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in products_left_steering_wheel %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product }}"/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h6 class="fw-bolder">{{ product|truncatewords:5 }}</h6>
                            <p>{{ product.power }} л.с, {{ product.volume }} АТ, {{ product.year_of_issue }} г.
                            {{ product.mileage }} км, {{ product.get_transmission_display }}</p>
                            <!-- Product price-->
                            <h6>{{ product.price }} сом</h6>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product-detail' product.id %}">Посмотреть</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p>Упс... Пока нет леворульных машин</p>
        {% endif %}

        <h2 class="fw-bolder mb-4">Машины коробка-автомат</h2>
        {% if products_transmission_automatic %}
        <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
            {% for product in products_transmission_automatic %}
            <div class="col mb-5">
                <div class="card h-100">
                    <!-- Product image-->
                    <img class="card-img-top" src="{{ product.image.url }}" alt="{{ product }}"/>
                    <!-- Product details-->
                    <div class="card-body p-4">
                        <div class="text-center">
                            <!-- Product name-->
                            <h6 class="fw-bolder">{{ product|truncatewords:5 }}</h6>
                            <p>{{ product.power }} л.с, {{ product.volume }} АТ, {{ product.year_of_issue }} г.
                            {{ product.mileage }} км, {{ product.get_transmission_display }}</p>
                            <!-- Product price-->
                            <h6>{{ product.price }} сом</h6>
                        </div>
                    </div>
                    <!-- Product actions-->
                    <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <div class="text-center"><a class="btn btn-outline-dark mt-auto" href="{% url 'product-detail' product.id %}">Посмотреть</a></div>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
        {% else %}
        <p>Упс... Пока нет леворульных машин</p>
        {% endif %}
    </div>
</section>
{% endblock %}

templates/search.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div role="main" style="padding: 60px 0 30px;">
	<section class="jumbotron text-center">
		<div class="container">
			<h1 class="jumbotron-heading">Результат(ы) поиска</h1>
			<p class="lead text-muted">
				Найдено <b>{{ products|length }}</b> искомое(ых) из запроса "{{ search }}".<br>
			</p>
			<p>
				<a href="{% url 'home' %}" class="btn btn-secondary my-2">Вернуться "Домой"</a>
			</p>
		</div>
	</section>

	<div class="album" style="outline: none;">
		<div class="container">
			<div class="row">
				{% for product in products %}
				<div class="col-md-4" style="margin: 0 auto;">
					<div class="card mb-4 box-shadow">
						<img class="card-img-top" src="{{ product.image.url }}" alt="{{ product }}">
						<div class="card-body">
							<p class="card-text">
							<h5 style="text-align: center; margin: 0 0 15px;">{{ product }}</h5>
							Год выпуска: {{ product.year_of_issue }},
							Пробег, км: {{ product.mileage }},
							Двигатель: {{ product.get_engine_display }},
							Объем двигателя, см3: {{ product.volume }},
							Мощность, л. с.: {{ product.power }} ...
							<hr>
							<h5 style="text-align: center; padding: 0 0 14px;">{{ product.price }} сом</h5>
							</p>
							<div class="d-flex justify-content-between align-items-center">
								<div class="btn-group">
									<a href="{% url 'update-product' product.id %}"
									   class="btn btn-sm btn-outline-secondary">Обновить</a>
									<a href="{% url 'product-detail' product.id %}"
									   class="btn btn-sm btn-outline-secondary">Перейти</a>
								</div>
								<small class="text-muted">{{ product.created }}</small>
							</div>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/update-product.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<!-- Раздел обновления продукта -->
<section class="py-5">
    <div class="container px-4 px-lg-5 mt-5">
        <div style="max-width: 500px; margin: 0 auto;">
            <h1 class="jumbotron-heading">Обновить данные продукта</h1>
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{ product_form|crispy }}
                {{ formset.management_form }}
                {% for form in formset %}
                    {{ form }}
                {% endfor %}
                <button type="submit" class="btn btn-secondary btn-lg btn-block" style="width: 100%; position: relative; top: 25px; margin-bottom: 50px;">Обновить</button>
            </form>
        </div>
    </div>
</section>
<!-- /Раздел обновления продукта -->
{% endblock %}